set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

FILE(GLOB SRC libgltf/*.cpp)

SOURCE_GROUP("" FILES ${SRC})

ADD_LIBRARY(gltf ${SRC})

ADD_LIBRARY(gltf::common ALIAS gltf)

INCLUDE_DIRECTORIES(${CMAKE_CURRENT_SOURCE_DIR})

TARGET_INCLUDE_DIRECTORIES(gltf
        INTERFACE
        $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}>
        $<INSTALL_INTERFACE:include>
)
