#!/bin/sh
### BEGIN INIT INFO
# Provides:          admin-executor-service
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/stop admin executor service
# Description:       tart/stop admin executor service
#  This script will start admin executor service
### END INIT INFO

NAME=admin-executor-service
DAEMON=/usr/local/sbin/ryzom_admin_service
RunningDirectory=/home/vagrant/admin_executor_service
ConfigDirectory=/home/vagrant/admin_executor_service
LogDirectory=/home/vagrant/admin_executor_service
PARAMS="--fulladminname=admin_executor_service --shortadminname=AES -A${RunningDirectory}"
PIDFILE=${RunningDirectory}/pid.state

case "$1" in
    start)
        start-stop-daemon --start --background --pidfile ${PIDFILE} --exec ${DAEMON} -- ${PARAMS}
        ;;
    stop)
        start-stop-daemon --stop --pidfile ${PIDFILE} --exec ${DAEMON}
        ;;
    status)
        start-stop-daemon --status --pidfile ${PIDFILE} --exec ${DAEMON}
        exit $?
        ;;
    *)
        echo "Usage: $0 {start|stop|status}" >&2
        exit 3
        ;;
esac

exit 0

# vim: syntax=sh ts=4 sw=4 sts=4 sr noet
