#!/usr/bin/env bash
### BEGIN INIT INFO
# Provides:          ryzom-shard
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/stop
# Description:       Start/stop
#  This script will start
### END INIT INFO

function shard() {
    local command=$1
    /etc/init.d/ryzom-admin ${command}
    /etc/init.d/ryzom-admin-executor ${command}
    /etc/init.d/ryzom-backup  ${command}
    /etc/init.d/ryzom-entities-game  ${command}
    /etc/init.d/ryzom-input-output  ${command}
    /etc/init.d/ryzom-naming  ${command}
}

case "$1" in
    start)
        shard start
        ;;
    stop)
        shard stop
        ;;
    status)
        shard status
        exit $?
        ;;
    *)
        echo "Usage: $0 {start|stop|status}" >&2
        exit 3
        ;;
esac

exit 0

# vim: syntax=sh ts=4 sw=4 sts=4 sr noet
