#!/bin/sh
### BEGIN INIT INFO
# Provides:          ryzom-admin-executor
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/stop admin executor service
# Description:       Start/stop admin executor service
#  This script will start admin executor service
### END INIT INFO

DAEMON=${BUILD_PATH}/bin/ryzom_admin_service
RunningDirectory=${SHARD_PATH}/admin_executor_service
PARAMS="--writepid --fulladminname=admin_executor_service --shortadminname=AES"
PIDFILE=${RunningDirectory}/pid.state

case "$1" in
    start)
        start-stop-daemon --start --background --oknodo --pidfile ${PIDFILE} --chdir ${RunningDirectory} --startas ${DAEMON} -- ${PARAMS}
        ;;
    stop)
        start-stop-daemon --stop --oknodo --pidfile ${PIDFILE}
        ;;
    status)
        start-stop-daemon --status --oknodo --pidfile ${PIDFILE}
        exit $?
        ;;
    *)
        echo "Usage: $0 {start|stop|status}" >&2
        exit 3
        ;;
esac

exit 0

# vim: syntax=sh ts=4 sw=4 sts=4 sr noet
